// data.js
export const medicalData = {
  "骨格 (頭部・体幹)": [
    { ja: "頭蓋骨", en: "skull", level: 1 },
    { ja: "前頭骨", en: "frontal bone", level: 2 },
    { ja: "頭頂骨", en: "parietal bone", level: 2 },
    { ja: "側頭骨", en: "temporal bone", level: 2 },
    { ja: "後頭骨", en: "occipital bone", level: 2 },
    { ja: "蝶形骨", en: "sphenoid bone", level: 3 },
    { ja: "篩骨", en: "ethmoid bone", level: 3 },
    { ja: "涙骨", en: "lacrimal bone", level: 3 },
    { ja: "鼻骨", en: "nasal bone", level: 2 },
    { ja: "鋤骨", en: "vomer", level: 3 },
    { ja: "下鼻甲介", en: "inferior nasal concha", level: 3 },
    { ja: "頬骨", en: "zygomatic bone", level: 2 },
    { ja: "上顎骨", en: "maxilla", level: 2 },
    { ja: "下顎骨", en: "mandible", level: 2 },
    { ja: "舌骨", en: "hyoid bone", level: 3 },
    { ja: "脊椎", en: "vertebra", level: 1 },
    { ja: "頸椎", en: "cervical vertebra", level: 2 },
    { ja: "環椎 (C1)", en: "atlas", level: 3 },
    { ja: "軸椎 (C2)", en: "axis", level: 3 },
    { ja: "胸椎", en: "thoracic vertebra", level: 2 },
    { ja: "腰椎", en: "lumbar vertebra", level: 2 },
    { ja: "仙骨", en: "sacrum", level: 2 },
    { ja: "尾骨", en: "coccyx", level: 2 },
    { ja: "胸骨", en: "sternum", level: 2 },
    { ja: "剣状突起", en: "xiphoid process", level: 3 },
    { ja: "肋骨", en: "rib", level: 1 },
    { ja: "肋軟骨", en: "costal cartilage", level: 2 }
  ],
  "骨格 (上肢・下肢)": [
    { ja: "鎖骨", en: "clavicle", level: 2 },
    { ja: "肩甲骨", en: "scapula", level: 2 },
    { ja: "肩峰", en: "acromion", level: 3 },
    { ja: "烏口突起", en: "coracoid process", level: 3 },
    { ja: "上腕骨", en: "humerus", level: 2 },
    { ja: "橈骨", en: "radius", level: 2 },
    { ja: "尺骨", en: "ulna", level: 2 },
    { ja: "肘頭", en: "olecranon", level: 3 },
    { ja: "手根骨", en: "carpal bones", level: 2 },
    { ja: "舟状骨", en: "scaphoid", level: 3 },
    { ja: "月状骨", en: "lunate", level: 3 },
    { ja: "中手骨", en: "metacarpal", level: 2 },
    { ja: "指骨", en: "phalanx", level: 2 },
    { ja: "骨盤", en: "pelvis", level: 1 },
    { ja: "腸骨", en: "ilium", level: 2 },
    { ja: "坐骨", en: "ischium", level: 2 },
    { ja: "恥骨", en: "pubis", level: 2 },
    { ja: "寛骨臼", en: "acetabulum", level: 3 },
    { ja: "大腿骨", en: "femur", level: 2 },
    { ja: "大転子", en: "greater trochanter", level: 3 },
    { ja: "膝蓋骨", en: "patella", level: 2 },
    { ja: "脛骨", en: "tibia", level: 2 },
    { ja: "腓骨", en: "fibula", level: 2 },
    { ja: "外果 (外くるぶし)", en: "lateral malleolus", level: 3 },
    { ja: "内果 (内くるぶし)", en: "medial malleolus", level: 3 },
    { ja: "足根骨", en: "tarsal bones", level: 2 },
    { ja: "距骨", en: "talus", level: 3 },
    { ja: "踵骨", en: "calcaneus", level: 3 }
  ],
  "筋肉": [
    { ja: "眼輪筋", en: "orbicularis oculi", level: 3 },
    { ja: "口輪筋", en: "orbicularis oris", level: 3 },
    { ja: "咬筋", en: "masseter", level: 3 },
    { ja: "胸鎖乳突筋", en: "sternocleidomastoid", level: 3 },
    { ja: "僧帽筋", en: "trapezius", level: 2 },
    { ja: "広背筋", en: "latissimus dorsi", level: 3 },
    { ja: "大胸筋", en: "pectoralis major", level: 2 },
    { ja: "前鋸筋", en: "serratus anterior", level: 3 },
    { ja: "三角筋", en: "deltoid", level: 2 },
    { ja: "上腕二頭筋", en: "biceps brachii", level: 2 },
    { ja: "上腕三頭筋", en: "triceps brachii", level: 2 },
    { ja: "腕橈骨筋", en: "brachioradialis", level: 3 },
    { ja: "腹直筋", en: "rectus abdominis", level: 2 },
    { ja: "腹斜筋", en: "oblique muscle", level: 2 },
    { ja: "横隔膜", en: "diaphragm", level: 1 },
    { ja: "大殿筋", en: "gluteus maximus", level: 2 },
    { ja: "中殿筋", en: "gluteus medius", level: 2 },
    { ja: "梨状筋", en: "piriformis", level: 3 },
    { ja: "大腰筋", en: "psoas major", level: 3 },
    { ja: "縫工筋", en: "sartorius", level: 3 },
    { ja: "大腿四頭筋", en: "quadriceps femoris", level: 2 },
    { ja: "ハムストリング", en: "hamstring", level: 2 },
    { ja: "前脛骨筋", en: "tibialis anterior", level: 3 },
    { ja: "腓腹筋", en: "gastrocnemius", level: 3 },
    { ja: "ヒラメ筋", en: "soleus", level: 3 },
    { ja: "アキレス腱", en: "achilles tendon", level: 1 }
  ],
  "循環器": [
    { ja: "心臓", en: "heart", level: 1 },
    { ja: "右心房", en: "right atrium", level: 2 },
    { ja: "右心室", en: "right ventricle", level: 2 },
    { ja: "左心房", en: "left atrium", level: 2 },
    { ja: "左心室", en: "left ventricle", level: 2 },
    { ja: "僧帽弁", en: "mitral valve", level: 3 },
    { ja: "三尖弁", en: "tricuspid valve", level: 3 },
    { ja: "大動脈弁", en: "aortic valve", level: 3 },
    { ja: "肺動脈弁", en: "pulmonary valve", level: 3 },
    { ja: "心膜", en: "pericardium", level: 3 },
    { ja: "大動脈", en: "aorta", level: 1 },
    { ja: "大動脈弓", en: "aortic arch", level: 3 },
    { ja: "上大静脈", en: "superior vena cava", level: 3 },
    { ja: "下大静脈", en: "inferior vena cava", level: 3 },
    { ja: "肺動脈", en: "pulmonary artery", level: 2 },
    { ja: "肺静脈", en: "pulmonary vein", level: 2 },
    { ja: "冠動脈", en: "coronary artery", level: 2 },
    { ja: "頸動脈", en: "carotid artery", level: 2 },
    { ja: "鎖骨下動脈", en: "subclavian artery", level: 3 },
    { ja: "腹部大動脈", en: "abdominal aorta", level: 3 },
    { ja: "門脈", en: "portal vein", level: 3 },
    { ja: "毛細血管", en: "capillary", level: 1 },
    { ja: "赤血球", en: "erythrocyte", level: 2 },
    { ja: "白血球", en: "leukocyte", level: 2 },
    { ja: "血小板", en: "thrombocyte", level: 3 }
  ],
  "消化器": [
    { ja: "口腔", en: "oral cavity", level: 2 },
    { ja: "唾液腺", en: "salivary gland", level: 2 },
    { ja: "食道", en: "esophagus", level: 1 },
    { ja: "胃", en: "stomach", level: 1 },
    { ja: "噴門", en: "cardia", level: 3 },
    { ja: "幽門", en: "pylorus", level: 3 },
    { ja: "小腸", en: "small intestine", level: 1 },
    { ja: "十二指腸", en: "duodenum", level: 2 },
    { ja: "空腸", en: "jejunum", level: 3 },
    { ja: "回腸", en: "ileum", level: 3 },
    { ja: "大腸", en: "large intestine", level: 1 },
    { ja: "盲腸", en: "cecum", level: 3 },
    { ja: "虫垂", en: "appendix", level: 2 },
    { ja: "結腸", en: "colon", level: 2 },
    { ja: "直腸", en: "rectum", level: 2 },
    { ja: "肛門", en: "anus", level: 1 },
    { ja: "肝臓", en: "liver", level: 1 },
    { ja: "胆嚢", en: "gallbladder", level: 2 },
    { ja: "総胆管", en: "common bile duct", level: 3 },
    { ja: "膵臓", en: "pancreas", level: 2 },
    { ja: "腹膜", en: "peritoneum", level: 3 }
  ],
  "脳・神経": [
    { ja: "大脳", en: "cerebrum", level: 2 },
    { ja: "前頭葉", en: "frontal lobe", level: 2 },
    { ja: "頭頂葉", en: "parietal lobe", level: 2 },
    { ja: "側頭葉", en: "temporal lobe", level: 2 },
    { ja: "後頭葉", en: "occipital lobe", level: 2 },
    { ja: "小脳", en: "cerebellum", level: 2 },
    { ja: "間脳", en: "diencephalon", level: 3 },
    { ja: "視床", en: "thalamus", level: 3 },
    { ja: "視床下部", en: "hypothalamus", level: 3 },
    { ja: "脳下垂体", en: "pituitary gland", level: 3 },
    { ja: "脳幹", en: "brainstem", level: 2 },
    { ja: "中脳", en: "midbrain", level: 3 },
    { ja: "橋", en: "pons", level: 3 },
    { ja: "延髄", en: "medulla oblongata", level: 3 },
    { ja: "脊髄", en: "spinal cord", level: 1 },
    { ja: "嗅神経 (I)", en: "olfactory nerve", level: 3 },
    { ja: "視神経 (II)", en: "optic nerve", level: 2 },
    { ja: "動眼神経 (III)", en: "oculomotor nerve", level: 3 },
    { ja: "滑車神経 (IV)", en: "trochlear nerve", level: 3 },
    { ja: "三叉神経 (V)", en: "trigeminal nerve", level: 3 },
    { ja: "外転神経 (VI)", en: "abducens nerve", level: 3 },
    { ja: "顔面神経 (VII)", en: "facial nerve", level: 2 },
    { ja: "内耳神経 (VIII)", en: "vestibulocochlear nerve", level: 3 },
    { ja: "舌咽神経 (IX)", en: "glossopharyngeal nerve", level: 3 },
    { ja: "迷走神経 (X)", en: "vagus nerve", level: 3 },
    { ja: "副神経 (XI)", en: "accessory nerve", level: 3 },
    { ja: "舌下神経 (XII)", en: "hypoglossal nerve", level: 3 },
    { ja: "坐骨神経", en: "sciatic nerve", level: 2 }
  ],
  "泌尿・生殖・内分泌": [
    { ja: "腎臓", en: "kidney", level: 1 },
    { ja: "腎盂", en: "renal pelvis", level: 3 },
    { ja: "尿管", en: "ureter", level: 2 },
    { ja: "膀胱", en: "urinary bladder", level: 2 },
    { ja: "尿道", en: "urethra", level: 2 },
    { ja: "精巣", en: "testis", level: 2 },
    { ja: "前立腺", en: "prostate", level: 2 },
    { ja: "卵巣", en: "ovary", level: 2 },
    { ja: "卵管", en: "fallopian tube", level: 3 },
    { ja: "子宮", en: "uterus", level: 2 },
    { ja: "甲状腺", en: "thyroid gland", level: 2 },
    { ja: "副甲状腺", en: "parathyroid gland", level: 3 },
    { ja: "副腎", en: "adrenal gland", level: 2 },
    { ja: "膵島 (ランゲルハンス島)", en: "pancreatic islets", level: 3 },
  ],
  "感覚器": [
    { ja: "角膜", en: "cornea", level: 2 },
    { ja: "強膜", en: "sclera", level: 3 },
    { ja: "虹彩", en: "iris", level: 2 },
    { ja: "瞳孔", en: "pupil", level: 1 },
    { ja: "水晶体", en: "lens", level: 2 },
    { ja: "網膜", en: "retina", level: 2 },
    { ja: "視神経乳頭", en: "optic disc", level: 3 },
    { ja: "黄斑", en: "macula", level: 3 },
    { ja: "鼓膜", en: "tympanic membrane", level: 2 },
    { ja: "耳小骨", en: "ossicles", level: 3 },
    { ja: "蝸牛", en: "cochlea", level: 3 },
    { ja: "三半規管", en: "semicircular canals", level: 3 },
    { ja: "耳管", en: "eustachian tube", level: 3 },
    { ja: "表皮", en: "epidermis", level: 2 },
    { ja: "真皮", en: "dermis", level: 2 },
    { ja: "皮下組織", en: "subcutaneous tissue", level: 3 },
  ]
};
